from .resnet import *
from .slimmable_nets import *
from .regnet import *
from .wideresnet import *
from .mlp import *
from .lenet import *
from .simple_cnns import *
from .moderate_cnns import *
from .lowrank_transformer import *